In [1]:
import pandas as pd

data = pd.read_excel("data/student_data.xlsx")

data.head()

,student_id,student_name,course,batch,semester,cgpa,attendance,aptitude_score,coding_score,communication_score,projects_count,internships,placed
0,1,Aarav Sharma,BTech,2021-2025,6,6.5,70,60,65,68,2,Yes,No
1,2,Ananya Verma,MCA,2022-2024,4,7.2,75,65,70,72,3,No,Yes
2,3,Rohan Singh,BTech,2021-2025,7,8.1,80,75,78,74,3,Yes,Yes
3,4,Priya Kumari,BCA,2022-2025,5,5.8,65,50,55,60,1,No,No
4,5,Aditya Gupta,MTech,2023-2025,3,9.0,90,85,88,86,4,Yes,Yes

In [2]:
import sqlite3

# Database create/connect
conn = sqlite3.connect("database/database.db")

cursor = conn.cursor()

print("Database connected successfully")

Database connected successfully

In [4]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER,
    student_name TEXT,
    course TEXT,
    batch TEXT,
    semester INTEGER,
    cgpa REAL,
    attendance INTEGER,
    aptitude_score INTEGER,
    coding_score INTEGER,
    communication_score INTEGER,
    projects_count INTEGER,
    internships TEXT,
    placed TEXT
)
""")

conn.commit()

print("Table created successfully")

Table created successfully

In [3]:
import pandas as pd

# Excel load
data = pd.read_excel("data/student_data.xlsx")

# SQL me insert
data.to_sql("students", conn, if_exists="replace", index=False)

print("Data inserted into SQL successfully")

Data inserted into SQL successfully

In [4]:
df = pd.read_sql("SELECT * FROM students", conn)

df.head()

,student_id,student_name,course,batch,semester,cgpa,attendance,aptitude_score,coding_score,communication_score,projects_count,internships,placed
0,1,Aarav Sharma,BTech,2021-2025,6,6.5,70,60,65,68,2,Yes,No
1,2,Ananya Verma,MCA,2022-2024,4,7.2,75,65,70,72,3,No,Yes
2,3,Rohan Singh,BTech,2021-2025,7,8.1,80,75,78,74,3,Yes,Yes
3,4,Priya Kumari,BCA,2022-2025,5,5.8,65,50,55,60,1,No,No
4,5,Aditya Gupta,MTech,2023-2025,3,9.0,90,85,88,86,4,Yes,Yes

In [5]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("database/database.db")
data = pd.read_sql("SELECT * FROM students", conn)

data.head()

,student_id,student_name,course,batch,semester,cgpa,attendance,aptitude_score,coding_score,communication_score,projects_count,internships,placed
0,1,Aarav Sharma,BTech,2021-2025,6,6.5,70,60,65,68,2,Yes,No
1,2,Ananya Verma,MCA,2022-2024,4,7.2,75,65,70,72,3,No,Yes
2,3,Rohan Singh,BTech,2021-2025,7,8.1,80,75,78,74,3,Yes,Yes
3,4,Priya Kumari,BCA,2022-2025,5,5.8,65,50,55,60,1,No,No
4,5,Aditya Gupta,MTech,2023-2025,3,9.0,90,85,88,86,4,Yes,Yes

# CLEANING

In [6]:
data['internships'] = data['internships'].replace({'Yes':1, 'No':0})
data['placed'] = data['placed'].replace({'Yes':1, 'No':0})
data['projects_count'] = data['projects_count'].replace({'Yes':1, 'No':0})

data['projects_count'] = pd.to_numeric(data['projects_count'])

In [9]:
data_clean = data.drop(['student_id','student_name','course','batch'], axis=1)

In [10]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   semester             500 non-null    int64
 1   cgpa                 500 non-null    float64
 2   attendance           500 non-null    int64
 3   aptitude_score       500 non-null    int64
 4   coding_score         500 non-null    int64
 5   communication_score  500 non-null    int64
 6   projects_count       500 non-null    int64
 7   internships          500 non-null    int64
 8   placed               300 non-null    float64
dtypes: float64(2), int64(7)
memory usage: 35.3 KB

In [19]:
data_clean = data_clean.dropna(subset=['placed'])

In [20]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   semester             300 non-null    int64
 1   cgpa                 300 non-null    float64
 2   attendance           300 non-null    int64
 3   aptitude_score       300 non-null    int64
 4   coding_score         300 non-null    int64
 5   communication_score  300 non-null    int64
 6   projects_count       300 non-null    int64
 7   internships          300 non-null    int64
 8   placed               300 non-null    float64
dtypes: float64(2), int64(7)
memory usage: 23.4 KB

In [21]:
X = data_clean.drop('placed', axis=1)
y = data_clean['placed']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

# Prediction

In [22]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]

# Accuracy

In [23]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 1.0

In [24]:
new_student = [[6, 8.5, 85, 75, 80, 78, 3, 1]]

In [25]:
result = model.predict(new_student)

if result[0] == 1:
    print("Placed ✅")
else:
    print("Not Placed ❌")

Placed ✅

D:\anaconda\New folder\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [28]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [29]:
import os
import pickle

os.makedirs('model', exist_ok=True)

with open('model/model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved successfully ✅")

Model saved successfully ✅

In [30]:
import pickle

# Load model
with open('model/model.pkl', 'rb') as f:
    model = pickle.load(f)

# Prediction function
def predict_placement(data):
    result = model.predict([data])
    
    if result[0] == 1:
        return "Placed ✅"
    else:
        return "Not Placed ❌"


# Test (optional)
if __name__ == "__main__":
    sample = [6, 8.5, 85, 75, 80, 78, 3, 1]
    print(predict_placement(sample))

Placed ✅

D:\anaconda\New folder\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(